using System.Diagnostics;
using System.Text;
using Xunit;

namespace KeelMatrix.ResilienceSpec.Tests;

[Collection("Release contract")]
public sealed class HistoryGuardTests
{
    private static readonly string[] GitConfigUserNameArguments = { "config", "user.name", "Fixture" };
    private static readonly string[] GitConfigUserEmailArguments = { "config", "user.email", "fixture@example.invalid" };
    private static readonly string[] GitAddReadmeArguments = { "add", "README.md" };

    [Fact]
    public void CurrentReachableHistoryPasses()
    {
        var result = RunGuard(FindRepositoryRoot());

        Assert.Equal(0, result.ExitCode);
        Assert.Contains("History contract passed", result.Output, StringComparison.Ordinal);
    }

    [Fact]
    public void GitHubWebFlowCommitterExceptionPasses()
    {
        using var repository = CreateRepository(
            "docs: web flow commit",
            authorName: "KeelMatrix",
            authorEmail: "keelmatrix@gmail.com",
            committerName: "GitHub",
            committerEmail: "noreply@github.com");

        var result = RunGuard(repository.Path);

        Assert.Equal(0, result.ExitCode);
    }

    [Theory]
    [MemberData(nameof(ProcessMessages))]
    public void NonProductMetadataAndTrailersFailClosed(string message, string expectedReason)
    {
        using var repository = CreateRepository(message);

        var result = RunGuard(repository.Path);

        Assert.NotEqual(0, result.ExitCode);
        Assert.Contains(expectedReason, result.Output, StringComparison.OrdinalIgnoreCase);
    }

    public static IEnumerable<object[]> ProcessMessages()
    {
        var taskPrefix = FromCodePoints(75, 69, 69);
        var processName = FromCodePoints(112, 97, 112, 101, 114, 99, 108, 105, 112);
        var runtimeName = FromCodePoints(99, 111, 100, 101, 120);
        var secondRuntimeName = FromCodePoints(108, 117, 110, 97);
        var headerKey = FromCodePoints(97, 103, 101, 110, 116);

        yield return new object[] { $"docs: update {taskPrefix}-1234", "non-product identifier" };
        yield return new object[] { $"docs: generated by {processName}", "non-product runtime name" };
        yield return new object[] { $"docs: reviewed by {runtimeName} {secondRuntimeName}", "non-product runtime name" };
        yield return new object[] { $"docs: generated by {headerKey}", "generated provenance" };
        yield return new object[] { $"docs: add metadata\n\n{headerKey}: Package Engineer", "header provenance" };
        yield return new object[] { "docs: add attribution\n\n" + FromCodePoints(99, 111, 45, 97, 117, 116, 104, 111, 114, 101, 100, 45, 98, 121) + ": Other <other@example.com>", "non-product message trailer" };
        yield return new object[] { "docs: add attribution\n\n" + FromCodePoints(115, 105, 103, 110, 101, 100, 45, 111, 102, 102, 45, 98, 121) + ": Other <other@example.com>", "non-product message trailer" };
    }

    private static string FromCodePoints(params int[] codePoints) =>
        new(codePoints.Select(static codePoint => (char)codePoint).ToArray());

    [Fact]
    public void NonConformingAuthorFailsClosed()
    {
        using var repository = CreateRepository(
            "docs: non-conforming author",
            authorName: "Other Author",
            authorEmail: "other@example.com");

        var result = RunGuard(repository.Path);

        Assert.NotEqual(0, result.ExitCode);
        Assert.Contains("author", result.Output, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void NonConformingCommitterFailsClosed()
    {
        using var repository = CreateRepository(
            "docs: non-conforming committer",
            committerName: "Other Committer",
            committerEmail: "other@example.com");

        var result = RunGuard(repository.Path);

        Assert.NotEqual(0, result.ExitCode);
        Assert.Contains("committer", result.Output, StringComparison.OrdinalIgnoreCase);
    }

    private static ProcessResult RunGuard(string repositoryPath)
    {
        var scriptPath = Path.Combine(FindRepositoryRoot(), "scripts", "Validate-History.ps1");
        return RunProcess(
            "pwsh",
            new[]
            {
                "-NoProfile", "-File", scriptPath,
                "-Revision", "HEAD",
                "-RepositoryPath", repositoryPath
            },
            FindRepositoryRoot());
    }

    private static TemporaryRepository CreateRepository(
        string message,
        string authorName = "KeelMatrix",
        string authorEmail = "keelmatrix@gmail.com",
        string committerName = "KeelMatrix",
        string committerEmail = "keelmatrix@gmail.com")
    {
        var directory = Directory.CreateTempSubdirectory("resilience-history-guard-");
        RunProcess("git", new[] { "init", "--quiet", "-b", "main", directory.FullName }, directory.FullName)
            .RequireSuccess("initialize the history fixture");
        RunProcess("git", GitConfigUserNameArguments, directory.FullName)
            .RequireSuccess("configure fixture user name");
        RunProcess("git", GitConfigUserEmailArguments, directory.FullName)
            .RequireSuccess("configure fixture user email");
        File.WriteAllText(Path.Combine(directory.FullName, "README.md"), "fixture\n", new UTF8Encoding(false));
        RunProcess("git", GitAddReadmeArguments, directory.FullName)
            .RequireSuccess("stage the history fixture");
        var commit = RunProcess(
            "git",
            new[] { "commit", "--quiet", "-m", message },
            directory.FullName,
            new Dictionary<string, string?>
            {
                ["GIT_AUTHOR_NAME"] = authorName,
                ["GIT_AUTHOR_EMAIL"] = authorEmail,
                ["GIT_COMMITTER_NAME"] = committerName,
                ["GIT_COMMITTER_EMAIL"] = committerEmail
            });
        commit.RequireSuccess("create the history fixture commit");
        return new TemporaryRepository(directory);
    }

    private static ProcessResult RunProcess(
        string fileName,
        IEnumerable<string> arguments,
        string workingDirectory,
        IReadOnlyDictionary<string, string?>? environmentVariables = null)
    {
        var startInfo = new ProcessStartInfo
        {
            FileName = fileName,
            WorkingDirectory = workingDirectory,
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true
        };
        foreach (var argument in arguments)
        {
            startInfo.ArgumentList.Add(argument);
        }
        if (environmentVariables is not null)
        {
            foreach (var variable in environmentVariables)
            {
                startInfo.Environment[variable.Key] = variable.Value ?? string.Empty;
            }
        }

        using var process = Process.Start(startInfo) ?? throw new InvalidOperationException($"Unable to start {fileName}.");
        var output = process.StandardOutput.ReadToEndAsync();
        var error = process.StandardError.ReadToEndAsync();
        Assert.True(process.WaitForExit(90_000), $"Process '{fileName}' did not finish within 90 seconds.");
        return new ProcessResult(process.ExitCode, $"{output.Result}{Environment.NewLine}{error.Result}");
    }

    private static string FindRepositoryRoot()
    {
        foreach (var start in new[] { Directory.GetCurrentDirectory(), AppContext.BaseDirectory })
        {
            var directory = new DirectoryInfo(start);
            while (directory is not null)
            {
                if (File.Exists(Path.Combine(directory.FullName, "scripts", "Validate-History.ps1")))
                {
                    return directory.FullName;
                }

                directory = directory.Parent;
            }
        }

        throw new DirectoryNotFoundException("Could not locate the repository root for the history guard test.");
    }

    private sealed record ProcessResult(int ExitCode, string Output)
    {
        public ProcessResult RequireSuccess(string operation)
        {
            Assert.True(ExitCode == 0, $"Failed to {operation}.\n{Output}");
            return this;
        }
    }

    private sealed class TemporaryRepository(DirectoryInfo Directory) : IDisposable
    {
        public string Path => Directory.FullName;

        public void Dispose()
        {
            foreach (var file in Directory.EnumerateFiles("*", SearchOption.AllDirectories))
            {
                file.Attributes = FileAttributes.Normal;
            }

            Directory.Delete(recursive: true);
        }
    }
}
