[CmdletBinding()]
param(
    [string]$RepositoryPath = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$includedExtensions = @('.cs', '.csproj', '.md', '.props', '.ps1', '.sh', '.targets', '.yml', '.yaml')
$excludedPaths = @(
    'scripts/Validate-DocumentationHygiene.ps1',
    'scripts/Validate-History.ps1',
    'scripts/Validate-CompatibilityContract.ps1',
    'tests/KeelMatrix.ResilienceSpec.Tests/HistoryGuardTests.cs',
    'tests/KeelMatrix.ResilienceSpec.Tests/DocumentationHygieneTests.cs',
    'tests/KeelMatrix.ResilienceSpec.Tests/CompatibilityContractTests.cs'
)
$forbiddenPatterns = @(
    @{ Pattern = '(?i)\b[A-Z]{2,10}-\d{2,}\b'; Label = 'internal task or issue identifier' },
    @{ Pattern = '(?i)\bpaperclip\b'; Label = 'orchestration product name' },
    @{ Pattern = '(?i)\b(?:codex|deepseek|chatgpt|claude|gpt(?:-\d+(?:\.\d+)?)?|sol|luna|ds\s+flash)\b'; Label = 'agent or model name' },
    @{ Pattern = '(?i)\bagents?\b'; Label = 'agent vocabulary' },
    @{ Pattern = '(?i)\b(?:orchestration|orchestrator|prompt(?:s)?|chain[- ]of[- ]thought|review process|frontier review)\b'; Label = 'orchestration or review-process vocabulary' },
    @{ Pattern = '(?i)\b(?:internal task identifiers?|issue identifiers?|model metadata|prohibited attribution|co-?author(?:ship)? trailers?|generated by agent)\b'; Label = 'non-product provenance wording' }
)

function Get-RelativePath {
    param([Parameter(Mandatory = $true)][string]$Path)

    return ([IO.Path]::GetRelativePath($RepositoryPath, $Path)).Replace('\', '/')
}

try {
    $violations = [Collections.Generic.List[string]]::new()
    foreach ($file in Get-ChildItem -LiteralPath $RepositoryPath -File -Recurse) {
        $relative = Get-RelativePath $file.FullName
        if ($relative.StartsWith('.git/', [StringComparison]::OrdinalIgnoreCase) -or
            $relative -match '(^|/)(?:artifacts|bin|obj)(?:/|$)' -or
            $excludedPaths -contains $relative -or
            $includedExtensions -notcontains $file.Extension.ToLowerInvariant()) {
            continue
        }

        $lines = @(Get-Content -LiteralPath $file.FullName)
        for ($lineNumber = 0; $lineNumber -lt $lines.Count; $lineNumber++) {
            foreach ($forbidden in $forbiddenPatterns) {
                if ($lines[$lineNumber] -match $forbidden.Pattern) {
                    $violations.Add("${relative}:$($lineNumber + 1): $($forbidden.Label)")
                }
            }
        }
    }

    if ($violations.Count -gt 0) {
        $violations | ForEach-Object { [Console]::Error.WriteLine($_) }
        throw "Documentation hygiene failed with $($violations.Count) violation(s)."
    }

    Write-Output 'Documentation hygiene passed: release-facing authored surfaces contain no non-product process language.'
    exit 0
}
catch {
    [Console]::Error.WriteLine($_.Exception.Message)
    exit 1
}
